services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app/api
      - ./shared:/app/shared
      - /app/node_modules
      - /app/shared/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app/app
      - ./shared:/app/shared
      - /app/node_modules
      - /app/shared/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  redis:
    image: redis:8.0-M03-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 3600 1 --save 300 100 --save 60 10000 --appendonly yes --appendfsync everysec
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
    driver: local
