name: App CI

on:
  push:
    paths:
      - "app/**"
      - "shared/**"
      - ".github/workflows/app-ci.yml"
      - ".eslintrc.json"
  pull_request:
    paths:
      - "app/**"
      - "shared/**"
      - ".github/workflows/app-ci.yml"
      - ".eslintrc.json"

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "app/.node-version"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            app/node_modules
            shared/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install shared dependencies
        working-directory: ./shared
        run: pnpm install --no-frozen-lockfile

      - name: Build shared package
        working-directory: ./shared
        run: pnpm build

      - name: Install app dependencies
        working-directory: ./app
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        working-directory: ./app
        run: pnpm lint

      - name: Run tests
        working-directory: ./app
        run: pnpm test

      - name: Build
        working-directory: ./app
        run: pnpm build
